--Schema for Vehicles Application
--version 0.1

DROP TABLE IF EXISTS manufacturer;

DROP TABLE IF EXISTS city;

CREATE TABLE IF NOT EXISTS city (
	CITY_CODE VARCHAR(5) NOT NULL PRIMARY KEY,
	CITY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS manufacturer (
	MNFR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	MNFR_NAME VARCHAR(50) NOT NULL,
	MNFR_ADDRESS_1 VARCHAR(100) NOT NULL,
	MNFR_ADDRESS_2 VARCHAR(100),
	MNFR_CITY_CODE VARCHAR(5) NOT NULL,
	MNFR_STATE_CODE VARCHAR(5) NOT NULL,
	MNFR_COUNTRY_CODE VARCHAR(5) NOT NULL,
	CONSTRAINT UK_MNFR_NAME UNIQUE KEY (MNFR_NAME),
	CONSTRAINT FK_MNFR_CITY FOREIGN KEY (MNFR_CITY_CODE) REFERENCES CITY (CITY_CODE)
);
